image: devops01.icico.net.ir/docker:01

stages:
  - deploy

deploy-dev:
  stage: deploy
  image: devops01.icico.net.ir/maven-3.6.1-jdk8:01
  only:
    - master
  script:
    - mvn -s .m2/settings.xml clean deploy -Dmaven.test.skip=true
